ACTIONS:
import librarier and data
basic checks
- colums
- basic statistics
- head
- check min value 0 in votes
- check voting districts per district - no obvious irregularities
- check dublicates
- check missing value
- drop fals column

In [36]:
# import librariers
import pandas as pd
import numpy as npa
import os

In [37]:
# defining path
path=r'/Users/ru/Desktop/CF/06_Achievement 6_VE'

In [38]:
# import data
df_ve = pd.read_csv(os.path.join(path,
'02_06_Data','2.2_06_Prepared Data','Berlin_VE21.kurz.csv'), sep=';', encoding='cp1252')

In [39]:
# check columns
print(df_ve.columns)

Index(['Stimmart', 'Adresse', 'BezNr', 'BezNa', 'WahlBez', 'WahlBezArt',
       'BriefwahlBez', 'AGHWK', 'BTWK', 'OstWest', 'Stimmber  total',
       'Stimmber A1', 'Stimmber A2', 'Stimmber A3', 'TeilN', 'TeilN B1',
       'Unglt Stimme', 'Glt Stimme', 'Stimme Ja', 'Stimme  Nein',
       'Unnamed: 20'],
      dtype='object')

In [41]:
# basic checks
df_ve.describe()

,BezNr,AGHWK,BTWK,Stimmber total,Stimmber A1,Stimmber A2,Stimmber A3,TeilN,TeilN B1,Unglt Stimme,Glt Stimme,Stimme Ja,Stimme Nein
count,3764.000000,3764.000000,3764.000000,3764.000000,3764.000000,3764.000000,3764.0,3764.000000,3764.000000,3764.000000,3764.000000,3764.000000,3764.000000
mean,6.420032,3.779756,80.718385,650.265675,398.191020,252.074655,0.0,477.765143,222.664718,12.396387,465.368757,275.225824,190.142933
std,3.344707,1.957726,3.347906,553.446467,344.651902,227.871178,0.0,148.012946,291.259404,13.466611,147.618660,103.111013,91.580899
min,1.000000,1.000000,75.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,2.000000,78.000000,0.000000,0.000000,0.000000,0.0,383.000000,4.000000,6.000000,370.000000,206.000000,123.000000
50%,6.000000,4.000000,81.000000,887.000000,530.000000,294.000000,0.0,451.500000,10.000000,11.000000,439.000000,259.000000,178.000000
75%,9.000000,5.000000,84.000000,1137.000000,674.250000,442.250000,0.0,536.000000,469.000000,16.000000,522.000000,326.000000,242.000000
max,12.000000,9.000000,86.000000,1793.000000,1219.000000,821.000000,0.0,1304.000000,1304.000000,436.000000,1288.000000,821.000000,749.000000

In [42]:
# ckeck votes and potential voters
df_ve[['Stimmber  total', 'Stimme Ja', 'Stimme  Nein']].describe()

       Stimmber  total    Stimme Ja  Stimme  Nein
count      3764.000000  3764.000000   3764.000000
mean        650.265675   275.225824    190.142933
std         553.446467   103.111013     91.580899
min           0.000000     0.000000      0.000000
25%           0.000000   206.000000    123.000000
50%         887.000000   259.000000    178.000000
75%        1137.000000   326.000000    242.000000
max        1793.000000   821.000000    749.000000

In [40]:
# check datatypes
df_ve.dtypes

Stimmart           object
Adresse            object
BezNr               int64
BezNa              object
WahlBez            object
WahlBezArt         object
BriefwahlBez       object
AGHWK               int64
BTWK                int64
OstWest            object
Stimmber  total     int64
Stimmber A1         int64
Stimmber A2         int64
Stimmber A3         int64
TeilN               int64
TeilN B1            int64
Unglt Stimme        int64
Glt Stimme          int64
Stimme Ja           int64
Stimme  Nein        int64
Unnamed: 20        object
dtype: object

In [43]:
# basic overview
df_ve.head(10)

,Stimmart,Adresse,BezNr,BezNa,WahlBez,WahlBezArt,BriefwahlBez,AGHWK,BTWK,OstWest,...,Stimmber A1,Stimmber A2,Stimmber A3,TeilN,TeilN B1,Unglt Stimme,Glt Stimme,Stimme Ja,Stimme Nein,Unnamed: 20
0,Stimme,01W100,1,Mitte,100,W,011A,1,75,W,...,880,741,0,519,12,11,508,299,209,NaN
1,Stimme,01W101,1,Mitte,101,W,011B,1,75,O,...,463,490,0,366,10,6,360,182,178,NaN
2,Stimme,01W102,1,Mitte,102,W,011B,1,75,O,...,591,692,0,406,10,8,398,217,181,NaN
3,Stimme,01W103,1,Mitte,103,W,011C,1,75,O,...,442,569,0,329,10,9,320,159,161,NaN
4,Stimme,01W104,1,Mitte,104,W,011D,1,75,O,...,638,639,0,522,17,10,512,263,249,NaN
5,Stimme,01W105,1,Mitte,105,W,011D,1,75,O,...,571,439,0,425,11,6,419,273,146,NaN
6,Stimme,01W106,1,Mitte,106,W,011E,1,75,O,...,670,758,0,536,2,10,526,248,278,NaN
7,Stimme,01W107,1,Mitte,107,W,011F,1,75,O,...,587,513,0,423,14,9,414,265,149,NaN
8,Stimme,01W108,1,Mitte,108,W,011E,1,75,O,...,499,548,0,363,12,4,359,186,173,NaN
9,Stimme,01W109,1,Mitte,109,W,011G,1,75,W,...,703,391,0,359,6,15,344,227,117,NaN

In [44]:
# check min value 0 in votes
min_value = df_ve['Stimme Ja'].min()
row_with_min = df_ve.loc[df_ve['Stimme Ja'] == min_value]

In [45]:
row_with_min

,Stimmart,Adresse,BezNr,BezNa,WahlBez,WahlBezArt,BriefwahlBez,AGHWK,BTWK,OstWest,...,Stimmber A1,Stimmber A2,Stimmber A3,TeilN,TeilN B1,Unglt Stimme,Glt Stimme,Stimme Ja,Stimme Nein,Unnamed: 20
1386,Stimme,05W332,5,Spandau,332,W,053V,3,78,W,...,0,0,0,0,0,0,0,0,0,05W331

it seems that there is one voting district listed which is not activ. no voters are registerd

In [46]:
# check voting districts per district - no obvious irregularities
df_ve['BezNa'].value_counts (dropna=False).sort_values(ascending=False)

BezNa
Charlottenburg-Wilmersdorf    361
Steglitz-Zehlendorf           352
Treptow-Köpenick              352
Neukölln                      346
Tempelhof-Schöneberg          332
Pankow                        331
Friedrichshain-Kreuzberg      317
Lichtenberg                   314
Mitte                         282
Marzahn-Hellersdorf           280
Spandau                       254
Reinickendorf                 243
Name: count, dtype: int64

In [47]:
# checking dublicates
df_dublic = df_ve[df_ve.duplicated()]

In [48]:
df_dublic

Empty DataFrame
Columns: [Stimmart, Adresse, BezNr, BezNa, WahlBez, WahlBezArt, BriefwahlBez, AGHWK, BTWK, OstWest, Stimmber  total, Stimmber A1, Stimmber A2, Stimmber A3, TeilN, TeilN B1, Unglt Stimme, Glt Stimme, Stimme Ja, Stimme  Nein, Unnamed: 20]
Index: []

[0 rows x 21 columns]

no dublicates found

In [49]:
# check for missing values
df_ve.isnull().sum()

Stimmart              0
Adresse               0
BezNr                 0
BezNa                 0
WahlBez               0
WahlBezArt            0
BriefwahlBez          0
AGHWK                 0
BTWK                  0
OstWest               0
Stimmber  total       0
Stimmber A1           0
Stimmber A2           0
Stimmber A3           0
TeilN                 0
TeilN B1              0
Unglt Stimme          0
Glt Stimme            0
Stimme Ja             0
Stimme  Nein          0
Unnamed: 20        3763
dtype: int64

In [50]:
# drop fals column: 'Unnamed: 20'
df_ve.drop(columns= ['Unnamed: 20'])

,Stimmart,Adresse,BezNr,BezNa,WahlBez,WahlBezArt,BriefwahlBez,AGHWK,BTWK,OstWest,Stimmber total,Stimmber A1,Stimmber A2,Stimmber A3,TeilN,TeilN B1,Unglt Stimme,Glt Stimme,Stimme Ja,Stimme Nein
0,Stimme,01W100,1,Mitte,100,W,011A,1,75,W,1621,880,741,0,519,12,11,508,299,209
1,Stimme,01W101,1,Mitte,101,W,011B,1,75,O,953,463,490,0,366,10,6,360,182,178
2,Stimme,01W102,1,Mitte,102,W,011B,1,75,O,1283,591,692,0,406,10,8,398,217,181
3,Stimme,01W103,1,Mitte,103,W,011C,1,75,O,1011,442,569,0,329,10,9,320,159,161
4,Stimme,01W104,1,Mitte,104,W,011D,1,75,O,1277,638,639,0,522,17,10,512,263,249
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3759,Stimme,12B6S,12,Reinickendorf,6S,B,126S,6,77,W,0,0,0,0,761,761,12,749,264,485
3760,Stimme,12B6T,12,Reinickendorf,6T,B,126T,6,77,W,0,0,0,0,449,449,7,442,127,315
3761,Stimme,12B6U,12,Reinickendorf,6U,B,126U,6,77,W,0,0,0,0,399,399,4,395,171,224
3762,Stimme,12B6V,12,Reinickendorf,6V,B,126V,6,77,W,0,0,0,0,373,373,4,369,175,194
3763,Stimme,12B6W,12,Reinickendorf,6W,B,126W,6,77,W,0,0,0,0,520,520,2,518,181,337

In [51]:
df_ve.to_csv(os.path.join(path, '02_06_Data','2.2_06_Prepared Data', 'df_ve_wrangled.csv'))